repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        additional_dependencies:
        - 'flake8-docstrings'
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
  - repo: https://github.com/iterative/dvc
    rev: 2.8.1
    hooks:
      - id: dvc-pre-commit
        language_version: python3
        stages:
          - commit
      - always_run: true
        id: dvc-post-checkout
        language_version: python3
        stages:
          - post-checkout